version: '3'

services:
    web:
        image: nginx:latest
        container_name: "euf_coding_web"
        volumes:
            - ./:/www
            - ./site.conf:/etc/nginx/conf.d/default.conf
        labels:
            - 'traefik.backend=euf_coding_web'
            - 'traefik.port=80'
            - 'traefik.frontend.rule=Host:euf.localhost'

    php:
        image: php:fpm
        container_name: "euf_coding_php"
        volumes:
            - ./:/www

    traefik:
        image: traefik:v1.7.16-alpine
        container_name: "euf_coding_traefik"
        command: -c /dev/null --web --docker --logLevel=INFO
        ports:
          - '8080:80'
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === 'e5325b19b381bfd88ce90a5ddb7823406b2a38cff6bb704b0acc289a09c8128d4a8ce2bbafcd1fcbdc38666422fe2806') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"